/**
 * Enum types for contracts
 */

/**
 * Status enum
 */
export type Status =
  | "STATUS_UNSPECIFIED"
  | "STATUS_SUCCESS"
  | "STATUS_ERROR"
  | "STATUS_PENDING"
  | "STATUS_IN_PROGRESS";

/**
 * Validation Level enum
 */
export type ValidationLevel =
  | "VALIDATION_LEVEL_UNSPECIFIED"
  | "VALIDATION_LEVEL_STRUCTURAL"
  | "VALIDATION_LEVEL_CONTRACT"
  | "VALIDATION_LEVEL_TYPESCRIPT"
  | "VALIDATION_LEVEL_BUILD"
  | "VALIDATION_LEVEL_HEALTH"
  | "VALIDATION_LEVEL_CONTRACT_DISCOVERY";

/**
 * Service Status enum
 */
export type ServiceStatus =
  | "SERVICE_STATUS_UNSPECIFIED"
  | "SERVICE_STATUS_PENDING"
  | "SERVICE_STATUS_GENERATING"
  | "SERVICE_STATUS_VALIDATED"
  | "SERVICE_STATUS_ERROR"
  | "SERVICE_STATUS_DEPLOYED"
  | "SERVICE_STATUS_DELETED";

/**
 * Deployment Status enum
 */
export type DeploymentStatus =
  | "DEPLOYMENT_STATUS_UNSPECIFIED"
  | "DEPLOYMENT_STATUS_PENDING"
  | "DEPLOYMENT_STATUS_IN_PROGRESS"
  | "DEPLOYMENT_STATUS_SUCCESS"
  | "DEPLOYMENT_STATUS_FAILED"
  | "DEPLOYMENT_STATUS_ROLLING_BACK"
  | "DEPLOYMENT_STATUS_ROLLED_BACK";

/**
 * Health Status enum
 */
export type HealthStatus =
  | "HEALTH_STATUS_UNSPECIFIED"
  | "HEALTH_STATUS_HEALTHY"
  | "HEALTH_STATUS_DEGRADED"
  | "HEALTH_STATUS_UNHEALTHY";

/**
 * Contract Error Type enum
 */
export type ContractErrorType =
  | "CONTRACT_ERROR_TYPE_UNSPECIFIED"
  | "CONTRACT_ERROR_TYPE_MISSING_CONTRACT"
  | "CONTRACT_ERROR_TYPE_MISSING_IMPLEMENTATION"
  | "CONTRACT_ERROR_TYPE_TYPE_MISMATCH";
