/**
 * Service name constants for NestJS Microservices
 */

export const GRAPH_SERVICE_NAME = "GRAPH_SERVICE";
export const CODEGEN_SERVICE_NAME = "CODEGEN_SERVICE";
export const DEPLOYMENT_SERVICE_NAME = "DEPLOYMENT_SERVICE";
export const INFRASTRUCTURE_SERVICE_NAME = "INFRASTRUCTURE_SERVICE";
export const BILLING_SERVICE_NAME = "BILLING_SERVICE";
