/**
 * Types for Factory Services
 */

import type {
  GeneratedConnectionCode,
  GeneratedRepositoryCode,
  GeneratedSchemaCode,
} from "./template-engine.types";

/**
 * Database components generated by DatabaseFactory
 */
export type DatabaseComponents = {
  connections: GeneratedConnectionCode[];
  schemas: GeneratedSchemaCode[];
  repositories: GeneratedRepositoryCode[];
};

/**
 * Messaging components generated by MessagingFactory
 */
export type MessagingComponents = {
  server: string;
  client?: string;
};

/**
 * Service components generated by ServiceFactory
 */
export type ServiceComponents = {
  main: string;
  appModule: string;
  database: DatabaseComponents;
  messaging: MessagingComponents;
  health: string;
};
